<?php
/**
 * Created by PhpStorm.
 * User: chira
 * Date: 19-01-2016
 * Time: 20:09
 */
$emailTo = "chiragbhatia94@gmail.com";

$sub = "Techfest IIT Bombay - Robotech Labs Workshops";

$body = <<<EOT
	<h2 style="line-height:normal;color:rgb(34,34,34);font-family:arial,sans-serif">Greetings from GeekFest!<br>Hello Chirag Bhatia ,&nbsp;</h2><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal">Congratulations. Your Team is successfully registered for GeekFest 2015-16</span><br style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal"><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal">scheduled to be held from <span class="aBn" data-term="goog_910887467" tabindex="0"><span class="aQJ">07th to 10th Jan, 2016</span></span>.</span><br>&nbsp;<table cellpadding="10" rules="all" style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal;border-color:rgb(102,102,102)">	<tbody>		<tr style="background:rgb(238,238,238)">			<td style="margin:0px"><strong>Name:</strong></td>			<td style="margin:0px">Chirag Bhatia</td>		</tr><tr><td style="margin:0px"><strong>GeekFest ID:</strong></td>
	<td style="margin:0px">FXS15-CH-15617
	</td>
	</tr>
	</tbody></table><br><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal">As per Information provided. Your Corresponding Team Includes :</span><br>&nbsp;<table border="1" cellpadding="1" cellspacing="1" style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal;width:500px">	<tbody>		<tr>			<td style="margin:0px;text-align:center"><b>Team Members</b></td>			<td style="margin:0px;text-align:center"><b>College</b></td>					</tr>		<tr>			<td style="margin:0px;text-align:center"><strong>Chirag Bhatia</strong></td>			<td style="margin:0px;text-align:center">Medicaps Institute of Science and Technology</td>					</tr>		<tr>			<td style="margin:0px;text-align:center"><strong>Harsh Rathi</strong></td>			<td style="margin:0px;text-align:center"><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal;text-align:center">Medicaps Institute of Science and Technology</span></td>					</tr>		<tr>			<td style="margin:0px;text-align:center"><strong>Arshita Jain</strong></td>			<td style="margin:0px;text-align:center"><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal;text-align:center">Medicaps Institute of Science and Technology</span></td>					</tr>		<tr>			<td style="margin:0px;text-align:center"><strong>Ayushi Chaturvedi</strong></td>			<td style="margin:0px;text-align:center"><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal;text-align:center">Medicaps Institute of Science and Technology</span></td>					</tr>		<tr>			<td style="margin:0px;text-align:center"><strong>Diksha Khanna</strong></td>			<td style="margin:0px;text-align:center"><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal;text-align:center">Medicaps Institute of Science and Technology</span></td>					</tr>	</tbody></table><br><strong>NOTE</strong>&nbsp;<strong>: College ID is Mandatory.</strong><br><br><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal">&nbsp;We are proud to present to you the fifth edition of our annual techno-cultural festival- GeekFest that is to be held from the&nbsp;<strong>7th</strong></span><strong style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal">&nbsp;to <span class="aBn" data-term="goog_910887468" tabindex="0"><span class="aQJ">10th of Jan, 2016</span></span></strong><span style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal">, the largest techno-cultural college festival in Central India.&nbsp;</span>
<p style="color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;line-height:normal"><br>Being an IIT, we are well-known for challenging problem statements in robotics, programming, civil design etc., and the brilliant cultural events in dance, drama, music which provide the perfect platform for all the creative artistes to exhibit their talent. For the Pronites which are the perfect amalgamation of excitement and fun, we plan to host fashion show on the 10th&nbsp;night which will be witnessing Miss India Asia Pacific 2014, Ms.Anukriti Gusain as the judge, EDM night by Sunburn Campus.<br><br><br>Do visit the website:<span style="color:#006400">&nbsp;</span><span style="color:#0000ff"><a href="http://www.geekfest.co.in" target="_blank">www.geekfest.co.in</a></span>&nbsp;<wbr>for more details on events.&nbsp;<br><br>Accommodations facilities are open on first come first serve&nbsp;basis.<br><br>GeekFest promises an inimitable world teeming with boundless merriment, talent and skill as you plunge into an experience of learning, exposure to top minds and unique ideas, and entertainment.&nbsp;<br><br>We hope to provide every individual with an exhilarating experience having a unique fusion of intellect and merriment, throughout the three days. It would be our pleasure to see you be a part of the festival.&nbsp;<br><br>Thank You !<br><br>Cheers !&nbsp;<br>Team GeekFest.</p>For Further Queries :<br>Contact<br>Govind Jakhetia<br><span class="skype_c2c_print_container notranslate">+91 7415373335</span><br>Counsil Manager.
EOT;

$headers = "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
$headers .= "From: Registration <noreply@geekfest.co.in>" . "\r\n" .
    "mailed-by: us.localpad.com";

mail($emailTo, $sub, $body, $headers);
?>